[package]
name = "light-merkle-tree-reference"
version = "1.0.0"
description = "Non-sparse reference Merkle tree implementation"
repository = "https://github.com/Lightprotocol/light-protocol"
license = "Apache-2.0"
edition = "2021"

[dependencies]
light-bounded-vec = { path = "../bounded-vec", version = "1.0.0" }
light-hasher = { path = "../hasher", version = "1.1.1" }
thiserror = "1.0"
log = "0.4.20"
