[package]
name = "light-test-utils"
version = "1.2.1"
description = "Utilities used in Light Protocol program tests"
repository = "https://github.com/Lightprotocol/light-protocol"
license = "Apache-2.0"
edition = "2021"

[features]
default = []
devenv = []

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }
solana-program-test = { workspace = true }
solana-sdk = { workspace = true }
thiserror = { workspace = true }
account-compression = { workspace = true }
light-compressed-token = { workspace = true }
light-system-program-anchor = { workspace = true }
light-registry = { workspace = true }
spl-token = { workspace = true, features = ["no-entrypoint"] }
light-prover-client = { workspace = true }
light-hasher = { workspace = true, features = ["anchor"] }
light-merkle-tree-reference = { workspace = true }
light-concurrent-merkle-tree = { workspace = true }
light-indexed-merkle-tree = { workspace = true }
light-compressed-account = { workspace = true }
light-program-test = { workspace = true }
forester-utils = { workspace = true }
light-sdk = { workspace = true, features = ["anchor"] }
rand = { workspace = true }
log = { workspace = true }
light-client = { workspace = true }
create-address-test-program = { workspace = true }
spl-token-2022 = { workspace = true }
light-batched-merkle-tree = { workspace = true }
light-merkle-tree-metadata = { workspace = true }
light-verifier = { workspace = true }
reqwest = { workspace = true }
light-account-checks = { workspace = true }
