[package]
name = "light-test-utils"
version = "1.2.1"
description = "Utilities used in Light Protocol program tests"
repository = "https://github.com/Lightprotocol/light-protocol"
license = "Apache-2.0"
edition = "2021"
publish = false

[features]
default = []
devenv = []
test-only = []

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
num-bigint = { workspace = true, features = ["rand"] }
num-traits = { workspace = true }
solana-sdk = { workspace = true }
thiserror = { workspace = true }
account-compression = { workspace = true, features = ["cpi"] }
light-compressed-token = { workspace = true, features = ["cpi"] }
light-ctoken-types = { workspace = true }
light-system-program-anchor = { workspace = true, features = ["cpi"] }
light-registry = { workspace = true, features = ["cpi"] }
spl-token = { workspace = true, features = ["no-entrypoint"] }
light-prover-client = { workspace = true, features = ["devenv"] }
light-hasher = { workspace = true, features = ["poseidon", "sha256", "keccak", "std"] }
light-merkle-tree-reference = { workspace = true }
light-concurrent-merkle-tree = { workspace = true }
light-indexed-merkle-tree = { workspace = true }
light-indexed-array = { workspace = true }
light-compressed-account = { workspace = true, features = ["std"] }
light-event = { workspace = true }
light-program-test = { workspace = true, features = ["devenv"] }
forester-utils = { workspace = true, features = ["devenv"] }
light-sdk = { workspace = true, features = ["anchor"] }
rand = { workspace = true }
log = { workspace = true }
light-client = { workspace = true, features = ["devenv"] }
create-address-test-program = { workspace = true }
spl-token-2022 = { workspace = true }
light-batched-merkle-tree = { workspace = true, features = ["test-only"] }
light-merkle-tree-metadata = { workspace = true }
reqwest = { workspace = true }
light-account-checks = { workspace = true }
light-sparse-merkle-tree = { workspace = true }
solana-banks-client = { workspace = true }
light-zero-copy = { workspace = true }
base64 = { workspace = true }
light-compressed-token-sdk = { workspace = true }
light-token-client = { workspace = true }
light-compressible = { workspace = true }
