[package]
name = "xtask"
version = "0.3.0"
edition = "2021"

[dependencies]
account-compression = { path = "../programs/account-compression", version = "0.5.0" }
anyhow = "1.0"
ark-bn254 = "0.4"
ark-ff = "0.4"
clap = { version = "4", features = ["derive"] }
groth16-solana = "0.0.3"
light-concurrent-merkle-tree = { path = "../merkle-tree/concurrent", version = "0.3.0" }
light-hash-set = { path = "../merkle-tree/hash-set", version = "0.3.0" }
light-hasher = { path = "../merkle-tree/hasher", version = "0.3.0" }
light-indexed-merkle-tree = { path = "../merkle-tree/indexed", version = "0.3.0" }
light-utils = { path = "../utils", version = "0.3.0" }
num-bigint = "0.4"
rand = "0.8"
quote = "1.0"
sha2 = "0.10"
solana-program = { workspace = true }
tabled = "0.15"
