[package]
name = "xtask"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0"
clap = { version = "4", features = ["derive"] }
light-hasher = { path = "../merkle-tree/hasher", version = "0.1.0" }
light-merkle-tree-program = { path = "../programs/merkle-tree", version = "0.3.1" }
light-merkle-tree-state = { path = "../state/merkle-tree" }
light-utils = { path = "../utils", version = "0.1.0" }
quote = "1.0"
sha2 = "0.10"
tabled = "0.15"
