[package]
name = "light-merkle-tree"
version = "0.1.1"
edition = "2021"
description = "Sparse Merkle tree implementation"
license = "Apache-2.0"

[dependencies]
anchor-lang = "0.28.0"
bytemuck = "1.13.1"

[dev-dependencies]
sha2 = "0.10"
