[package]
name = "photon-api"
version = "0.54.0"
description = "Solana indexer for general compression"
license = "Apache-2.0"
edition = "2021"

[dependencies]
progenitor-client = "0.9"
futures = "0.3"
reqwest = { version = "0.12", default-features = false, features = ["json", "stream", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["serde", "v4"] }
http = "1.0"
bytes = "1.0"
chrono = { version = "0.4", features = ["serde"] }
regress = ">=0.10, <0.10.4"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
wiremock = "0.6"

[build-dependencies]
progenitor = "0.9"
openapiv3 = "2.0"
serde_yaml = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
syn = "2.0"
prettyplease = "0.2"
