[package]
name = "photon-api"
version = "0.54.0"
description = "Solana indexer for general compression"
license = "Apache-2.0"
edition = "2021"

[dependencies]
progenitor-client = "0.12"
reqwest = { version = "0.13", default-features = false, features = ["json", "stream", "rustls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
wiremock = "0.6"

[build-dependencies]
progenitor = "0.12"
openapiv3 = "2.0"
serde_yaml = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
syn = "2.0"
prettyplease = "0.2"
