[package]
name = "photon-api"
version = "0.52.0"
authors = ["OpenAPI Generator team and contributors"]
description = "Solana indexer for general compression"
license = "Apache-2.0"
edition = "2018"

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_with = "^3.12"
serde_json = "^1.0"
url = "^2.2"
uuid = { version = "^1.0", features = ["serde", "v4"] }
[dependencies.reqwest]
version = "^0.12"
features = ["json", "multipart"]
