[package]
name = "changelog-test"
version = "1.0.0"
description = "Test program for changelog functionality"
repository = "https://github.com/Lightprotocol/light-protocol"
license = "Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "changelog_test"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
test-sbf = []
default = []

[dependencies]
light-sdk = { workspace = true }
light-sdk-types = { workspace = true }
light-hasher = { workspace = true, features = ["solana"] }
solana-program = { workspace = true }
light-macros = { workspace = true, features = ["solana"] }
borsh = { workspace = true }
light-compressed-account = { workspace = true, features = ["solana"] }
changelog = { path = "../../program-libs/changelog" }
light-zero-copy = { workspace = true }
light-account-checks = { workspace = true }

[dev-dependencies]
light-program-test = { workspace = true, features = ["devenv"] }
tokio = { workspace = true }
solana-sdk = { workspace = true }

[lints.rust.unexpected_cfgs]
level = "allow"
check-cfg = [
    'cfg(target_os, values("solana"))',
    'cfg(feature, values("frozen-abi", "no-entrypoint"))',
]
