[package]
name = "light-utils"
version = "1.1.0"
description = "Common utility functions used in Light Protocol"
repository = "https://github.com/Lightprotocol/light-protocol"
license = "Apache-2.0"
edition = "2021"

[features]
default = []
anchor = ["anchor-lang"]

[dependencies]
anyhow = { workspace = true }
ark-ff = { workspace = true }
ark-bn254 = { workspace = true }
light-hasher = { workspace = true }
num-bigint = { workspace = true, features = ["rand"] }
thiserror = { workspace = true }
solana-program = { workspace = true }
rand = { workspace = true }
zerocopy = { workspace = true, features = ["derive"] }
borsh = { workspace = true }
bytemuck = { workspace = true }
anchor-lang = { workspace = true, optional = true }

[dev-dependencies]
light-poseidon = { workspace = true }
borsh = { workspace = true }
