[package]
name = "light-bounded-vec"
version = "0.2.0"
description = "Bounded and cyclic vector implementations"
repository = "https://github.com/Lightprotocol/light-protocol"
license = "Apache-2.0"
edition = "2021"

[features]
solana = ["solana-program"]

[dependencies]
bytemuck = { version = "1.14", features = ["min_const_generics"] }
memoffset = "0.9"
solana-program = { version = "1.18.11", optional = true }
thiserror = "1.0"

[dev-dependencies]
rand = "0.8"
