[package]
name = "psp-account-compression"
version = "0.3.1"
description = "Light Protocol on-chain program which manages Merkle trees"
license = "GPL-3.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "psp_account_compression"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
test-bpf = []

[dependencies]
anchor-lang = "0.28.0"
anchor-spl = "0.28.0"

byteorder = "1.3"
bytemuck = { version = "1.14", features = ["min_const_generics"] }

arrayref = "0.3.6"
borsh = "0.9.1"
getrandom = { version = "0.2.2", features = ["custom"] }
solana-security-txt = "1.1.0"
ark-ff = { version = "^0.4.2", default-features = false }
bincode = "1.3.3"

# Light dependencies
aligned-sized = { version = "0.1.0", path = "../../macros/aligned-sized" }
light-concurrent-merkle-tree = { version = "0.1.0", path = "../../merkle-tree/concurrent" }
light-hasher = { path = "../../merkle-tree/hasher", version = "0.1.0" }
light-indexed-merkle-tree = { path = "../../merkle-tree/indexed", version = "0.1.0" }

light-utils = { version = "0.1.0", path = "../../utils" }
light-macros = { version = "0.3.1", path = "../../macros/light" }

# TODO: Remove once https://github.com/solana-labs/solana/issues/33504 is resolved.
ahash = "=0.8.6"
ark-serialize = "^0.4.0"

[dev-dependencies]
solana-program-test = "1.16.16"
solana-sdk = "1.16.16"
serde_json = "1.0.59"
ark-groth16 ={ version = "^0.3.0", default-features = false, features = ["std"] }
ark-serialize = { version = "^0.3.0", default-features = false }
tokio = "1.35.1"
