[package]
name = "light-token"
version = "0.4.0"
edition = { workspace = true }
description = "SDK for Light Tokens"
license = "Apache-2.0"
repository = "https://github.com/Lightprotocol/light-protocol"

[features]
default = []
v1 = ["light-compressed-token-sdk/v1"]
anchor = ["anchor-lang", "light-token-types/anchor", "light-token-interface/anchor", "light-compressed-token-sdk/anchor", "dep:light-sdk-macros"]
# idl-build feature enables IDL generation for client-side tooling and SDK generation
idl-build = ["anchor", "anchor-lang/idl-build", "light-sdk/idl-build", "light-compressed-token-sdk/idl-build"]
cpi-context = ["light-sdk/cpi-context", "light-compressed-token-sdk/cpi-context"]

profile-program = [
    "light-program-profiler/profile-program",
    "light-compressed-account/profile-program",
    "light-token-interface/profile-program",
    "light-compressed-token-sdk/profile-program",
]
profile-heap = [
    "light-program-profiler/profile-heap",
    "light-compressed-account/profile-heap",
    "light-token-interface/profile-heap",
    "light-compressed-token-sdk/profile-heap",
]

[dependencies]
# Light Protocol dependencies
light-compressed-token-sdk = { workspace = true }
light-token-types = { workspace = true }
light-compressed-account = { workspace = true, features = ["std", "solana"] }
light-compressible = { workspace = true }
light-token-interface = { workspace = true }
light-sdk = { workspace = true, features = ["v2", "cpi-context"] }
light-account = { workspace = true }
light-batched-merkle-tree = { workspace = true }
light-macros = { workspace = true }
thiserror = { workspace = true }
# Serialization
borsh = { workspace = true }
solana-msg = { workspace = true }
# Solana dependencies
solana-pubkey = { workspace = true, features = ["sha2", "curve25519"] }
solana-instruction = { workspace = true }
solana-account-info = { workspace = true }
solana-cpi = { workspace = true }
solana-program-error = { workspace = true }
arrayvec = { workspace = true }
spl-pod = { workspace = true }
light-account-checks = { workspace = true, features = ["solana"] }
light-sdk-types = { workspace = true, features = ["v2"] }
light-zero-copy = { workspace = true }
light-program-profiler = { workspace = true }

# Optional Anchor dependency
anchor-lang = { workspace = true, optional = true }
light-sdk-macros = { workspace = true, optional = true }

[dev-dependencies]
light-account-checks = { workspace = true, features = ["test-only", "pinocchio", "std"] }
anchor-lang = { workspace = true }
light-compressed-token = { workspace = true, features = ["idl-build"] }
pinocchio = { workspace = true }


[lints.rust.unexpected_cfgs]
level = "allow"
check-cfg = [
    'cfg(target_os, values("solana"))',
    'cfg(feature, values("frozen-abi", "no-entrypoint"))',
]
