[package]
name = "system-test"
version = "1.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "system_test"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
test-sbf = []
custom-heap = []
default = ["custom-heap"]

[dependencies]


[dev-dependencies]
light-program-test = { workspace = true, features = ["devenv"] }
light-test-utils = { workspace = true, features = ["devenv"] }
tokio = { workspace = true }
light-prover-client = { workspace = true }
anchor-lang = { workspace = true }
light-system-program = { workspace = true }
account-compression = { workspace = true }
light-hasher = { workspace = true }
light-compressed-account = { workspace = true }
light-client = { workspace = true }
light-sdk = { workspace = true }
light-verifier = { workspace = true }
light-registry = { workspace = true }
solana-cli-output = { workspace = true }
serde_json = "1.0.138"
solana-sdk = { workspace = true }
quote.workspace = true
serial_test = { workspace = true }
light-batched-merkle-tree = { workspace = true }
light-merkle-tree-metadata = { workspace = true }
light-bloom-filter = { workspace = true }
light-utils = { workspace = true }
