[package]
name = "system-test"
version = "1.1.0"
description = "Created with Anchor"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "lib"]
name = "system_test"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
test-sbf = []
custom-heap = []
default = ["custom-heap"]

[dependencies]


[dev-dependencies]
light-system-program-pinocchio = { path = "../../programs/system", features = [
    "cpi",
] }
light-program-test = { workspace = true, features = ["devenv"] }
light-test-utils = { workspace = true, features = ["devenv"] }
tokio = { workspace = true }
light-prover-client = { workspace = true, features = ["devenv"] }
anchor-lang = { workspace = true }
light-system-program-anchor = { workspace = true, features = ["cpi"] }
account-compression = { workspace = true, features = ["cpi"] }
light-hasher = { workspace = true, features = ["poseidon"] }
light-compressed-account = { workspace = true, features = ["anchor"] }
light-client = { workspace = true, features = ["devenv"] }
light-sdk = { workspace = true, features = ["anchor"] }
light-verifier = { workspace = true }
light-registry = { workspace = true }
solana-cli-output = { workspace = true }
serde_json = "1.0.140"
solana-sdk = { workspace = true }
quote.workspace = true
serial_test = { workspace = true }
light-batched-merkle-tree = { workspace = true }
light-merkle-tree-metadata = { workspace = true, features = ["anchor"] }
light-bloom-filter = { workspace = true }
pinocchio = { workspace = true }
light-account-checks = { workspace = true, features = ["test-only", "pinocchio"] }
