[package]
name = "verifier_program_one"
version = "0.1.0"
description = "Verifier program 1 can verify 10 inputs and 2 outputs without additional public inputs."
license = "GPL-3.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "verifier_program_one"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { git = "https://github.com/coral-xyz/anchor", rev = "1c6f86e5f7793ce6adefe9cbfa11939647c509ce" }
anchor-spl = { git = "https://github.com/coral-xyz/anchor", rev = "1c6f86e5f7793ce6adefe9cbfa11939647c509ce" }
solana-program = "=1.16.1"
solana-security-txt = "1.1.0"
merkle_tree_program = { path = "../merkle_tree_program", features = ["cpi"] }

# Light Deps
groth16-solana = "0.0.1"
light-macros = "0.1.0"
light-verifier-sdk = {path = "../../../light-verifier-sdk"}
