[package]
name = "merkle_tree_program"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "merkle_tree_program"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
test-bpf = []

[profile.test]
opt-level = 2

[dependencies]
anchor-lang = "0.25.0"
anchor-spl = "0.25.0"

byteorder = "1.3"

#solana
solana-program = { path = "../../../../solana_pr_updated/solana/sdk/program"}

arrayref = "0.3.6"
borsh = "0.9.1"
getrandom = { version = "0.2.2", features = ["custom"] }
spl-token = { version = "3.2", features = [ "no-entrypoint" ] }
solana-security-txt = "0.1.0"
#crypto
ark-crypto-primitives = { version = "^0.3.0", default-features = true, features = [ "r1cs" ] }
ark-ff = { version = "^0.3.0", default-features = false }
ark-ec = { version = "0.3.0" }
ark-ed-on-bn254 = { version = "^0.3.0", features = ["r1cs"] }
ark-bn254 = "0.3.0"
ark-std = { version = "^0.3.0", default-features = false }
ark-relations = { version = "^0.3.0", default-features = false  }
bincode = "1.3.3"
#poseidon
arkworks-gadgets = "0.3.14"

[dev-dependencies]
solana-program-test = "1.9.16"
solana-sdk = "1.9.16"
serde_json = "1.0.59"
ark-groth16 ={ version = "^0.3.0", default-features = false, features = ["std"] }
ark-serialize = { version = "^0.3.0", default-features = false }
