[package]
name = "verifier_program_two"
version = "0.1.0"
description = "Verifier program 2 can verify 4 inputs and 4 outputs without 2 public inputs."
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "verifier_program_two"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "0.26.0"}
anchor-spl = "0.26.0"
solana-security-txt = "0.1.0"
merkle_tree_program = { path = "../merkle_tree_program", features = ["cpi"] }

#solana
solana-program = { path = "../../../../solana/sdk/program"}

# Light Deps
groth16-solana = {path = "../../../groth16-solana"}
light-verifier-sdk = {path = "../../../light-verifier-sdk"}
