[package]
name = "sdk-anchor-test"
version = "0.7.0"
description = "Test program for Light SDK and Light Macros"
edition = "2021"
license = "Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib", "lib"]
name = "sdk_anchor_test"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
test-sbf = []
bench-sbf = []
idl-build = ["anchor-lang/idl-build", "light-sdk/idl-build"]

[dependencies]
# Needs to be imported for LightHasher
light-hasher = { workspace = true, features = ["solana", "poseidon", "sha256", "std"] }
anchor-lang = { workspace = true }
light-sdk = { workspace = true, features = ["anchor", "v2", "poseidon"] }
light-sdk-types = { workspace = true }
serial_test = { workspace = true }
solana-pubkey = { workspace = true }

[target.'cfg(not(target_os = "solana"))'.dependencies]
solana-sdk = { workspace = true }

[dev-dependencies]
light-client = { workspace = true, features = ["devenv"] }
light-program-test = { workspace = true, features = ["devenv"] }
light-test-utils = { workspace = true, features = ["devenv"] }
light-prover-client = { workspace = true, features = ["devenv"] }
tokio = { workspace = true }
light-compressed-account = { workspace = true, features = ["solana"] }
