[package]
name = "light-ctoken-types"
version = "0.2.1"
edition = "2021"
description = "ctoken and compressed token types for Light Protocol"
license = "Apache-2.0"
repository = "https://github.com/Lightprotocol/light-protocol"

[features]
anchor = [
    "anchor-lang",
    "light-compressed-account/anchor",
    "light-sdk-types/anchor",
]

[dependencies]
borsh = { workspace = true }
light-macros = { workspace = true }
anchor-lang = { workspace = true, optional = true }
light-sdk-types = { workspace = true }
light-account-checks = { workspace = true }
light-compressed-account = { workspace = true, features = ["std"] }
thiserror = { workspace = true }
solana-msg = { workspace = true }
