CU_LIMIT=1_000_000
RPC_POOL_SIZE=20
MAX_RETRIES=5
RETRY_DELAY=1000
RETRY_TIMEOUT=120_000
INDEXER_BATCH_SIZE=50
INDEXER_MAX_CONCURRENT_BATCHES=50
TRANSACTION_BATCH_SIZE=1
TRANSACTION_MAX_CONCURRENT_BATCHES=50
SLOT_UPDATE_INTERVAL_SECONDS=30TREE_DISCOVERY_INTERVAL_SECONDS=5
STATE_QUEUE_START_INDEX=0
STATE_QUEUE_LENGTH=28807
ADDRESS_QUEUE_START_INDEX=0
ADDRESS_QUEUE_LENGTH=28807
