[package]
name = "light-token-types"
version = "0.22.0"
edition = "2021"
description = "Light token sdk types"
license = "Apache-2.0"
repository = "https://github.com/Lightprotocol/light-protocol"

[features]
anchor = [
    "anchor-lang",
    "light-compressed-account/anchor",
    "light-sdk-types/anchor",
]
idl-build = ["anchor-lang/idl-build", "anchor", "light-sdk-types/idl-build"]

[dependencies]
borsh = { workspace = true }
light-macros = { workspace = true }
anchor-lang = { workspace = true, optional = true }
light-sdk-types = { workspace = true, features = ["std"] }
light-account-checks = { workspace = true }
light-compressed-account = { workspace = true, features = ["std"] }
thiserror = { workspace = true }
solana-msg = { workspace = true }
