[package]
name = "sp1-circuits-script"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "prove"
path = "src/main.rs"

[dependencies]
sp1-sdk = { workspace = true }
sp1-circuits-lib = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
hex = "0.4"
bincode = "1.3"

[build-dependencies]
sp1-build = { workspace = true }
