[package]
name = "light-compressed-token-sdk"
version = "0.1.0"
edition = { workspace = true }

[features]

anchor = ["anchor-lang", "light-compressed-token-types/anchor",  "light-ctoken-types/anchor"]
cpi-context = ["light-sdk/cpi-context"]
profile-program = [
    "light-program-profiler/profile-program",
    "light-compressed-account/profile-program",
    "light-ctoken-types/profile-program",
]
profile-heap = [
    "light-program-profiler/profile-heap",
    "light-compressed-account/profile-heap",
    "light-ctoken-types/profile-heap",
]

[dependencies]
# Light Protocol dependencies
light-compressed-token-types = { workspace = true }
light-compressed-account = { workspace = true, features = ["std"] }
light-ctoken-types = { workspace = true }
light-sdk = { workspace = true, features = ["v2"] }
light-macros = { workspace = true }
thiserror = { workspace = true }
# Serialization
borsh = { workspace = true }
solana-msg = { workspace = true }
# Solana dependencies
solana-pubkey = { workspace = true, features = ["sha2", "curve25519"] }
solana-instruction = { workspace = true }
solana-account-info = { workspace = true }
solana-cpi = { workspace = true }
solana-program-error = { workspace = true }
arrayvec = { workspace = true }
spl-token-2022 = { workspace = true }
spl-pod = { workspace = true }
light-account-checks = { workspace = true, features = ["solana"] }
light-sdk-types = { workspace = true, features = ["v2"] }
light-zero-copy = { workspace = true }
light-program-profiler = { workspace = true }

# Optional Anchor dependency
anchor-lang = { workspace = true, optional = true }

[dev-dependencies]
light-account-checks = { workspace = true, features = ["test-only", "pinocchio", "std"] }
anchor-lang = { workspace = true }
light-compressed-token = { workspace = true }
pinocchio = { workspace = true }


[lints.rust.unexpected_cfgs]
level = "allow"
check-cfg = [
    'cfg(target_os, values("solana"))',
    'cfg(feature, values("frozen-abi", "no-entrypoint"))',
]
